### ISSUE TITLE
Repetitive update request example?

### ISSUE THREAD

**Issue by Nakilon** [abachman/p5.websocket#17]
As I understand the sketch.js makes the example page receive the update only on mouse click.
How do I properly make it request updates N times per second? I'm noob in JS.

UPD: for now I put the `sendMessage({});` at the end of `draw()` in my project.

**Comment by abachman** [comment]
Hi! 👋🏻  

I like explaining things, so I'm just going to launch into it, but you can skip to the question at the bottom if you already know all this. :D

It sounds like you expect an update to happen somewhere else and want to make sure your sketch knows about it as soon as it happens?

When building systems like this (client + server communicating in real time), we call this **polling**. Your code knows something _could_ happen, but won't receive notification of something happening automatically, so it checks every once in awhile to see if something happened. In this case, high frequency checks, about 30 times per second by default. 

That's okay for one client at a time, but imagine 100 people loading the sketch in their own browsers. Very few low end web hosts--like https://chat.reasonable.systems, the server behind the example code--can handle 30,000 messages per second 😬.

The alternative to polling is **publish/subscribe**, which is what this system is built for. The p5.websockets library opens a connection to the server and waits (quietly) for updates to happen. Messages are only sent through the system when something interesting happens and there's an update every connected sketch needs to know about. 

In the case of the example sketch, an update only happens when someone clicks somewhere on the sketch on their machine. 100 other people could open the page on their computers, but a message only needs to be sent when someone interacts. We could do this with any sort of momentary interaction. A key press, hovering over a shape, an interesting moment in a physics simulation, or clicking the "send" button in a chat client, for example.

Unfortunately, this means the library + server setup is a much better fit for turn taking types of games or art sketches which rely on brief bursts of interaction. You can see some more example sketches on https://chat.reasonsable.systems.

---

the question: what sort of sketch are you trying to build?

**Comment by Nakilon** [comment]
I made this https://github.com/Nakilon/wsui
The purpose is multiple as you can see described in README.
Here you can see the html/js code I came up with: https://github.com/Nakilon/wsui/blob/b2c60b6bcdbf5be6c95770a05756ec202842621a/lib/wsui.rb#L46
The examples in README are three turn-based and one (Collatz conjecture verifier) that should update the view as frequently as I want (one passes the fps parameter in his ruby project) so it could be used as an interface to monitor an arbitrary long-running task.

**Comment by abachman** [comment]
Nice! That's wild, very interesting technique for doing a standalone app with the server baked in. Also, clever use of generic javascript to handle multiple app ideas. With the way this is set up, I can see how the regular updates to animate the UI make sense.

You caught me on a free weekend, and it's a problem space I've been interested in for awhile, and you put some interesting new code in front of me, so I'm writing a bit of a blog post. 😸  Feel free to ignore.

---

Here's a sequence diagram of the conversation between WSUI and the browser when the browser code uses polling:

```mermaid
sequenceDiagram
    WSUI->>browser-1: HTML + JS
    browser-1-->>WSUI: sendMessage({})
    WSUI->>browser-1: data
    browser-1-->>WSUI: sendMessage({})
    WSUI->>browser-1: data (no change)
    Note over WSUI,browser-2: browser-2 joins
    WSUI->>browser-2: HTML + JS
    browser-2-->>WSUI: sendMessage({}) 
    WSUI->>browser-1: data (no change)
    WSUI->>browser-2: data
    browser-1-->>WSUI: sendMessage({})
    WSUI->>browser-1: data (no change)
    WSUI->>browser-2: data (no change)
``` 

You can see how each new participant joining the conversation and triggering their own `sendMessage` events in a loop increases the total number of messages _every_ participating client receives. `browser-2 sendMessage({})` causes the server to send data to browser-2 _and_ browser-1. Even if we dropped `sendMessage({})` to once-per-second, each new client using the service triggers an update to every client using the service. After 30 or 40 I bet we'd see problems with browsers stuttering and the server slowing down.

A push-based system totally cuts out this kind of amplification of messages:

```mermaid
sequenceDiagram
    WSUI->>browser-1: HTML + JS
    Note over WSUI: time passes
    WSUI->>browser-1: data
    Note over WSUI,browser-2: browser-2 joins
    WSUI->>browser-2: HTML + JS
    Note over WSUI: more time passes
    WSUI->>browser-1: data
    WSUI->>browser-2: data 
```

WSUI still has to send data to every connected client, but it can choose when to send data, for example, only when the data has changed or when there is something interesting to report.    

I forked your project and sent a PR (https://github.com/Nakilon/wsui/pull/1) demonstrating push-based messaging and changes to the collatz example that show how it works. That seemed easier than pasting git diffs into this conversation.

The key idea I flipped around is that instead of clients triggering UI updates by sending a message, the server code publishes updates to all connected clients whenever something happens. In this case, the collatz example sketch calls `app.publish` at the end of every `loop`. 

The reason this pattern is interesting is that now you can connect many clients without placing very much extra load on the system. 

---

To answer the original question, I also added a technique for triggering `sendMessage({})` from the javascript code that gives you a little more control of frequency. `setInterval(callback, time)` [is a function built into browsers](https://developer.mozilla.org/en-US/docs/Web/API/setInterval) which calls the `callback` function every `time` milliseconds. So instead of having to slow the p5js framerate to avoid crashing the server, you can let p5js run at full speed and have the client (in browser) sketch call `sendMessage({})` only a few times per second.

**Comment by Nakilon** [comment]
Woah! Didn't even know GitHub has some sort of UML.
I'll dive into your "server load reduction" idea and the PR when I can.

**Comment by abachman** [comment]
> Woah! Didn't even know GitHub has some sort of UML.

Yeah! They're built in the [mermaid](https://mermaid.js.org/) language with <code>```mermaid</code> code blocks. [GitHub has only supported it for the last year or so](https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/). 

So much nicer than generating graphiz images or screenshots of drawings.
